# Generated by Django 5.1.2 on 2024-10-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='liga',
            field=models.CharField(choices=[('Hacker', 'Hacker'), ('Coder', 'Coder'), ('Gamer', 'Gamer')], default='Hacker', max_length=10),
        ),
    ]
