# Generated by Django 5.1.2 on 2024-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='liga',
            field=models.CharField(choices=[('Hacker', 'Hacker'), ('Coder', 'Coder'), ('Gamer', 'Gamer')], default='Gamer', max_length=10),
        ),
    ]
